---
abstract: "interface to Linux's C<PF_PACKET> socket family"
author:
  - 'Paul Evans <leonerd@leonerd.org.uk>'
build_requires:
  ExtUtils::CBuilder: 0
  ExtUtils::CChecker: 0
  IO::Socket::INET: 0
  Module::Build: 0
  Module::Build::Compat: 0
  Test::More: 0
configure_requires:
  ExtUtils::CChecker: 0.04
  Module::Build: 0
  Module::Build::Compat: 0
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.113640'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Socket-Packet
provides:
  IO::Socket::Packet:
    file: lib/IO/Socket/Packet.pm
    version: 0.09
  Socket::Packet:
    file: lib/Socket/Packet.pm
    version: 0.09
requires:
  Exporter: 5.57
resources:
  license: http://dev.perl.org/licenses/
version: 0.09
